# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-15 23:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribers', models.IntegerField()),
                ('views', models.IntegerField()),
                ('popularity', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('category', models.ManyToManyField(help_text='Select a category', to='flexfeed.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sm_links', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(help_text='The social media site this post was made on.', max_length=50)),
                ('text', models.CharField(help_text='The text in the social media post.', max_length=500)),
                ('picture', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(help_text='The company that has this stock value.', max_length=50)),
                ('value', models.BigIntegerField(help_text='The value of the stock.')),
                ('trend', models.IntegerField(help_text='0 if trending down, 1 if trending up.')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular user', primary_key=True, serialize=False)),
                ('first_name', models.TextField(help_text='Enter your first name')),
                ('last_name', models.TextField(help_text='Enter your last name')),
                ('username', models.CharField(help_text='Enter your username (max 15 characters): ', max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(help_text='Enter your password: ', max_length=30)),
                ('profile_picture', models.URLField()),
                ('groups', models.ManyToManyField(help_text='Select a group', to='flexfeed.Group')),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='post',
            field=models.ManyToManyField(help_text='Select a post for this member', to='flexfeed.Post'),
        ),
        migrations.AddField(
            model_name='member',
            name='stock',
            field=models.ForeignKey(help_text='Select a stock for this member', on_delete=django.db.models.deletion.CASCADE, to='flexfeed.Stock'),
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(help_text='Select a member', to='flexfeed.Member'),
        ),
    ]
