# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-27 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexfeed', '0002_remove_post_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='link',
            field=models.URLField(default='', max_length=20000),
        ),
    ]
