# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-27 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexfeed', '0004_post_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(default=1, help_text='Enter a post description', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='site',
            field=models.CharField(default='', help_text='The social media site this post was made on.', max_length=50),
        ),
    ]
