# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexfeed', '0009_auto_20171031_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='picture',
            field=models.URLField(default='', max_length=20000),
        ),
    ]
