# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-02 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexfeed', '0012_auto_20171121_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='trend',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='value',
        ),
        migrations.AddField(
            model_name='stock',
            name='market',
            field=models.CharField(default='', help_text='The market containing this company (i.e. NASDAQ).', max_length=50),
        ),
        migrations.AddField(
            model_name='stock',
            name='symbol',
            field=models.CharField(default='', help_text="The company's market symbol (i.e. AAPL).", max_length=50),
        ),
    ]
